steps:
- name: 'gcr.io/abstract-web-393206/image'
  args: ['clone', 'https://github.com/ramanamurthy123456/ram.git']
- name: 'gcr.io/abstract-web-393206/image'
  args: ['build', '-t', 'gcr.io/abstract-web-393206/image:v3', '.']
images: ['gcr.io/abstract-web-393206/image:v3']
options:
  logging: CLOUD_LOGGING_ONLY
