# cloudbuild.yaml

steps:
  # Install Jupyter nbconvert
  - name: 'python'
    entrypoint: 'bash'
    args:
    - '-c'
    - 'pip install nbconvert'

  # Clone the repository
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', '.']

  # Convert the Jupyter Notebook to Python script
  - name: 'python'
    entrypoint: 'bash'
    args:
    - '-c'
    - 'jupyter nbconvert --to script your_notebook.ipynb'

  # Install dependencies if needed
  - name: 'python'
    entrypoint: 'bash'
    args:
    - '-c'
    - 'pip install -r requirements.txt'

  # Run the Python script
  - name: 'python'
    entrypoint: 'bash'
    args:
    - '-c'
    - 'python your_notebook.py'
