  # Step 1: Clone the Git repository
steps:
- name: 'gcr.io/cloud-builders/git'
  args: ['clone', 'https://github.com/ramanamurthy123456/ram.git']
 
  # Step 2: Run the Python script
- name: 'gcr.io/cloud-builders/python'
  args: ['main.py']

