# cloudbuild.yaml


options:
  logging: "CLOUD_LOGGING_ONLY"


steps:
  # Install dependencies, such as Python and required libraries
  - name: 'python'
    entrypoint: 'bash'
    args:
    - '-c'
    - 'apt-get update && apt-get install -y python3 python3-pip'

  # Clone the repository
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', '.']

  # Install requirements
  - name: 'python'
    entrypoint: 'bash'
    args:
    - '-c'
    - 'pip3 install -r requirements.txt'

  # Convert and execute the train.ipynb file
  - name: 'python'
    entrypoint: 'bash'
    args:
    - '-c'
    - 'jupyter nbconvert --to script train.ipynb && python3 train.py'

  # Convert and execute the deploy.ipynb file
  - name: 'python'
    entrypoint: 'bash'
    args:
    - '-c'
    - 'jupyter nbconvert --to script deploy.ipynb && python3 deploy.py'

  # Convert and execute the predict.ipynb file
  - name: 'python'
    entrypoint: 'bash'
    args:
    - '-c'
    - 'jupyter nbconvert --to script predict.ipynb && python3 predict.py'
