steps:
- name: 'gcr.io/cloud-builders/git'
  args: ['clone', 'https://github.com/ramanamurthy123456/ram.git']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/abstract-web-393206/image:1', './ram/ram/']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - 'image'
  - '--image'
  - 'gcr.io/abstract-web-393206/image:1'
  - '--region'
  - 'us-central1'
  - '--allow-unauthenticated'
images: ['gcr.io/abstract-web-393206/image:1']
options:
  logging: CLOUD_LOGGING_ONLY
